#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Получаем текущую ветку
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "Запуск линтера и тестов перед пушем в ветку main"

  npm run lint:ts
  npm run lint:scss
  npm run test:unit
fi