name: Linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install dependencies    
        run: npm ci

      - name: Testing TypeScript
        run: npm run lint:ts
        
      - name: build project
        run: npm run build:prod

      - name: Testing style lint 
        run: npm run lint:scss

      - name: Testing unit 
        run: npm run test:unit

      - name: Testing loki screenshots
        run: npm run test:ui:ci
  deploy:
      needs: CI
    # Specify runner + deployment step
      runs-on: ubuntu-latest
      steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PROJECT_SECRET }}
          publish_dir: ./build
