name: Linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install dependencies    
        run: npm ci

      - name: Testing TypeScript
        run: npm run lint:ts

      - name: Testing style lint 
        run: npm run lint:scss

      - name: Testing unit 
        run: npm run test:unit

      - name: Testing loki 
        run: npm build-storybook && npm test:ui --requireReference --reactUri file:./storybook-static # Необходимо указать команду для этого шага
