name: Linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
 push:
  branches: [main]
 pull_request:
  branches:  [main]
jobs:
  CI/CD:
    runs-on: ubuntu-latest
    strategy:
     matrix: 
     node-version: [17.x]
    steps:
   - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci

    - name: Testing typescript
    - run: npm lint:ts

    - name: Testing style lint 
    - run: npm lint:scss

    - name: Testing unit 
    - run: npm test:unit

     - name: Testing loki 
    - run: npm storybook
    - run: npm test:ui

   